version: '3.8'

services:
  traefik:
    # https://doc.traefik.io/traefik/
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

networks:
  traefik:
    name: "traefik"
    external: false