version: '3.8'

services:
  traefik:
    environment:
      # https://doc.traefik.io/traefik/reference/static-configuration/env/
      - TRAEFIK_API_INSECURE=false
      - TRAEFIK_API_DASHBOARD=false
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_WATCH=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_SWARMMODE=false
      - TRAEFIK_ENTRYPOINTS_web=true
      - TRAEFIK_ENTRYPOINTS_web_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_websecure=true
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSSOLVER=true
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSSOLVER_ACME_EMAIL
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSSOLVER_ACME_TLSCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSSOLVER_ACME_STORAGE=acme.json