#!/bin/bash

apt update

curl -fsSL https://get.docker.com -o get-docker.sh && \
  sh get-docker.sh && \
  rm get-docker.sh

curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o docker-compose && \
  chmod +x docker-compose && \
  mv docker-compose /usr/local/lib/docker-compose

adduser docker-user -q --disabled-password --disabled-login
groupadd docker
usermod -aG docker docker-user

echo ""
echo "You can now run docker with the non-root user: docker-user"
echo "> su docker-user"