#!/bin/bash

apt-get update

apt-get install -y \
  dbus-user-session \
  uidmap \
  systemd-container \
  docker-ce-rootless-extras

curl -fsSL https://get.docker.com -o get-docker.sh && \
  sh get-docker.sh && \
  rm get-docker.sh

adduser docker-user -q --disabled-password

machinectl shell docker-user@

dockerd-rootless-setuptool.sh install
loginctl enable-linger $(whoami)

echo ""
echo "You can now run docker with the non-root user: docker-user"
echo "> machinectl shell docker-user@"